# Generated by Django 4.1.11 on 2023-09-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_work_link_alter_work_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='works',
            field=models.ManyToManyField(related_name='artists', to='demoapp.work'),
        ),
    ]
